### ISSUE TITLE
Should `put` accept a units parameter?

### ISSUE THREAD

**Issue by maxcountryman** [mixmaxhq/cloudwatch-metrics#13]
I'm wondering about this because I have a pattern where I have my namespace defined such:

```js
myNamespace = new cloudwatchMetrics.Metric('MyNamespace', 'Count');
```

This works as long as I'm happy with the units I've specified. But what happens when I want to store latency in milliseconds with my metric? It's the same namespace, just a different type of unit.

Maybe it would be nice to be able to do something like:

```js
myNamespace.put(200, 'Latency', 'Milliseconds');
```

Any thoughts?

**Comment by jotto** [comment]
(3rd party observer) I had the same observation, the interface here seems a little unnatural: one cloudwatchMetric instance per unit type.
